= Hibernate 7 & JPA 3.2
:toc: auto

== Intro

https://hibernate.org/orm/releases/7.0/[Hibernate 7], sorti le 19/05 implémente https://projects.eclipse.org/projects/ee4j.jpa/releases/3.2[JPA dans sa version 3.2], sorti le 30/04.

Ces deux releases majeures apportent leur lot de nouveautés, certaines mêmes incontournables.

L'étude présente les features, en utilisant nativement JPA et Hibernate, sans Spring Data ou autre librairie.

D'une part, Spring n'est pour le moment pas compatible JPA 3.2/Hibernate 7 (https://spring.io/blog/2024/10/01/from-spring-framework-6-2-to-7-0[compatibilité prévue pour Spring 7] et https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-4.0-Release-Notes[Spring Boot 4]), d'autre part, pour mieux comprendre les nouveaux mécanismes de Hibernate et JPA il est plus pertinent de mettre de côté une surcouche comme Spring Data JPA.

L'étude contient un projet Java 21 servant d'exemple aux nouveautés. Il se consacre davantage à Hibernate plutôt qu'à JPA. Le starter web de Spring Boot est utilisé, uniquement pour la partie injection de dépendance et avoir une IHM d'administration de la base de données h2 embarquée. +
Ni Spring Data JPA ni Spring JDBC ou autre librairie que Hibernate sont utilisées pour l'accès à la BDD.

== https://in.relation.to/2024/04/01/jakarta-persistence-3/[JPA 3.2]

=== Configuration

Historiquement, JPA se configurait uniquement depuis un fichier `persistence.xml`.

JPA 3.2 propose une configuration par du code.

[source,java]
----
EntityManagerFactory emf =
    new PersistenceConfiguration("Bookshop")
                .nonJtaDataSource("java:global/jdbc/BookshopData")
                .managedClass(Book.class)
                .property(PersistenceConfiguration.LOCK_TIMEOUT, 5000)
                .createEntityManagerFactory();
----

L'objet peut être déclaré dans un bean Spring par exemple. +
Ensuite, on peut déclarer un `EntityManager` qu'on utilise de manière habituelle avec JPA :

[source,java]
----
EntityManager em = emf.createEntityManager();
try (EntityManager em = emf.createEntityManager()) {
    em.getTransaction().begin();

    em.persist(...);
    em.find(..., ...);

    em.getTransaction().commit();
} catch (Exception e) {
    em.getTransaction().rollback();
}

----

.Résumé
****
Cette évolution peut rendre possible la création d'une configuration JPA dynamique, ce qui n'était pas possible depuis un XML statique.
****

=== Méthodes de gestion automatique des transaction

L' `EntityManager` (et une connexion native `JDBC`) a un cycle de vie à respecter. Pour chaque opération, une transaction doit être ouverte, puis commit si la/les requête(s) sont OK, rollback le cas échéant avec un `try{} catch(){}`. Pour éviter de devoir gérêr ce cycle de vie manuellement, JPA propose des nouvelles méthodes fonctionnelles :

- `EntityManagerFactory.runInTransaction` : gère automatiquement le cycle de vie de `EntityManager`, pour les requêtes sans retour (INSERT, DELETE, UPDATE)
- `EntityManagerFactory.callInTransaction`: gère automatiquement le cycle de vie de `EntityManager`, pour les requêtes avec retour (SELECT)
- `EntityManager.runWithConnection` : *À partir d'un `EntityManager`*, gère le cycle de vie d'une connexion JDBC, pour des requêtes SQL natives

Ces fonctions prennent chacune une lambda : l'opération de bdd à exécuter. La transaction est gérée automatiquement pour plus de lisibilité.

[source,java]
----
/** runInTransaction quand il s'agit d'une requête qui ne retourne rien **/
entityManagerFactory.runInTransaction( entityManager -> {
    Book b = entityManager.find(Book.class, id);
    entityManager.remove(b);
});

/** callInTransaction quand il s'agit d'une requête avec un retour, un SELECT par exemple **/
Book b = entityManagerFactory.callInTransaction( entityManager -> {
    return entityManager.find(Book.class, id);
});

/** Et runWithConnection, quand du SQL natif doit être joué (procédure stockée par exemple)
    attention, runWithConnection nécessite un EntityManager et non EntityManagerFactory !
    On peut justement chainer EntityManagerFactory.runInTransaction et EntityManager.runWithConnection !  **/
entityManagerFactory.runInTransaction(em ->
    em.runWithConnection(connection -> {
        try (Statement s = ((Connection) connection).createStatement()) {
            s.execute("SELECT 1 FROM DUAL");
        }

        try (PreparedStatement s = ((Connection) connection).prepareStatement("SELECT * FROM DUAL WHERE DUMMY = ?")) {
            s.setString(1, "X");
            s.execute();
        }

        try (CallableStatement s = ((Connection) connection).prepareCall("{call package(?)}")) {
            s.setString(1, "arg");
            s.execute();
        }
    })
);
----

.Résumé
****
Cette nouvelle feature est la bienvenue, elle rend la gestion de transaction et session bien plus simple et automatique, globalement est code est bien plus lisible, sans le moindre compromis.
****

=== Metamodel

Le `Metamodel` existe depuis JPA 2, pour une présentation courte de la fonctionnalité, voir : <<note2>>.

Premièrement, avec JPA 3.2, l'artifactId de la dépendance Hibernate change. Avant cette version, il fallait utiliser la dépendance `hibernate-jpamodelgen`, maintenant renommée `hibernate-processor`.

Les nouveautés sont les constantes contenant le nom des propriétés, entityGraphs nommés, requêtes nommées, mapping de resulset SQL natif. Là où le metamodel était pratique lors de l'utilisation de l'API Criteria, il est désormais tout aussi pratique sur l'utilisation de JPQL, SQL natif, ...

Les nouvelles propriétés du métamodel :
[source,java]
----
@StaticMetamodel(Shop.class)
public abstract class Shop_ {
    // ...
    public static final String ID = "id";
    public static final String ADDRESS = "address";
    public static final String OWNER = "owner";
    public static final String EMPLOYEES = "employees";
    public static final String BOOKS = "books";
    public static final String QUERY_SHOP_FIND_ALL_BY_OWNER_ID = "Shop.findAllByOwnerId";
    public static final String GRAPH_SHOP_WITH_EMPLOYEES_NATIVE_JPA = "Shop.withEmployees.nativeJpa";
    // ...
}
----

L'entité :
[source,java]
----
@NamedEntityGraph(
        name = "Shop.withEmployees.nativeJpa",
        attributeNodes = @NamedAttributeNode("employees")
)
@NamedQuery(name = "Shop.findAllByOwnerId", query = "SELECT s FROM Shop s WHERE s.owner.id = :id")
public class Shop {
    @Id
    @GeneratedValue
    private Long id;

    @Embedded
    private Address address;

    // ...
}
----

L'utilisation de ces nouvelles propriétés, depuis la classe metamodel `Shop_` :
[source,java]
----
// Dans l'entité
@ManyToMany(mappedBy=Shop_.AUTHORS, fetch = FetchType.LAZY)
Collection<Person> employees;

// Dans le service
List<Shop> shops =  this.sessionFactory.callInTransaction( em ->
        // Le nom de la NamedQuery
        em.createNamedQuery(Shop_.QUERY_SHOP_FIND_ALL_BY_OWNER_ID)
                // Le nom de la colonne ID
                .setParameter(Shop_.ID, ownerId)
                // Le nom de l'EntityGraph
                .setHint("jakarta.persistence.fetchgraph", Shop_.GRAPH_SHOP_WITH_EMPLOYEES_NATIVE_JPA)
                .getResultList());
----

.Résumé
****
Le metamodel s'enrichit. +
En principe, il se génère automatiquement et permet de s'affranchir de certains problèmes, donc il n'y a absolument aucune raison à ne pas l'utiliser. Maintenant que tous les objets "nommés" sont disponibles (propriétés/colonnes, entity graphs, requêtes, mapping SQL), l'utilisation du metamodel est bien plus cohérente et on peut au maximum éviter les strings / types en durs.

Point regrettable levé plus tard, il s'agit ici du metalmodel JPA, donc seulement les objets "JPA" sont disponibles dans les classes métamodel. Le `@NamedEntityGraph` Hibernate (et non JPA) ne remonte pas dans le metamodel.
****

=== Options

Lors d'appels JPA (que ce soit par Criterias, JPQL ou depuis l'EntityManager), il est possible de passer certains "hints", c-a-d des options, par exemple :

[source, java]
----
var book =
        em.find(Book.class, isbn,
                Map.of("jakarta.persistence.cache.retrieveMode",
                            CacheRetrieveMode.BYPASS,
                       "jakarta.persistence.query.timeout", 500,
                       "org.hibernate.readOnly", true);
----

Dans le cadre de l'`EntityManager` et sur les appels des méthodes `find()`, `lock()` et `refresh()`, ces "hints" peuvent maintenant prendre la forme de variables, plutôt que key/values non type safe.
[source, java]
----
var book =
        em.find(Book.class, isbn, CacheRetrieveMode.BYPASS,
                Timeout.milliseconds(500), READ_ONLY);
----

.Résumé
****
L'impact de cette amélioration est limité. +
Elle ne concerne que les appels par `EntityManager`. Lors d'utilisation de JPQL ou Criterias, il faut toujours passer par les hints "à l'ancienne".
****

=== EntityGraph

Les `EntityGraph` existent depuis JPA 2.1, voir <<note2>>.

La fonctionnalité est très pratique pour contourner le problème N+1 mais souvent mise de côté de part sa difficulté de prise en main et sa verbosité.

Un entity graph peut être défini à partir d'une annotation.

Dans l'exemple ci-dessous : pour charger pour les projets, uniquement les départements des employés

[source, java]
----
@NamedEntityGraph(name = "project.employees",
    // on charge l'association employees
	attributeNodes = @NamedAttributeNode(
		value = "employees",
		subgraph = "project.employees.department"
	),
    // dans les employés, on charge la propriété département
	subgraphs = @NamedSubgraph(
		name = "project.employees.department",
		attributeNodes = @NamedAttributeNode("department")
	)
)
----

Ou au travers de définition d'objet avec l'API JPA et son ancienne version :
[source, java]
----
// Initialisation de l'entity graph
EntityGraph<Project> eg = em.createEntityGraph(Project.class);
// Récupération du noeud / association employees
// Pas type safe malgré le type générique!
Subgraph<Employee> employeeSg = eg.addSubgraph("employees");
// Récupération du département pour les employés
employeeSg.addAttributeNodes("department");

Query<Project> query = em.createQuery(
    "SELECT p FROM Project p", Project.class
);
query.setHint("javax.persistence.fetchgraph", graph);

List<Project> results = query.getResultList();
----

L'annotation JPA `@NamedEntityGraph` est inchangée, ici, c'est la 2e solution, l'API JPA qui subit quelques améliorations :

* Les méthodes sont type safe
* L'API peut utiliser le metamodel

L'équivalent avec JPA 3.2 est :
[source, java]
----
// Initialisation de l'entity graph
EntityGraph<Shop> eg = em.createEntityGraph(Project.class);
// Récupération du noeud / association employees
// Une nouvelle fonction addElementSubgraph est disponible,
// pouvant prendre l'attribut du metamodel type safe !
Subgraph<Employee> employeeSg = eg.addElementSubgraph(Project_.employees);
// Récupération de la propriété
// idem, on peut utiliser le metamodel pour être type safe
employeeSg.addAttributeNodes(Employee_.department);


// On peut chaîner les appels pour que ce soit plus clair
eg.addElementSubgraph(Project_.employees)
        .addAttributeNodes(Employee_.department);

return em.createQuery("FROM Project", Project.class)
        .setHint("jakarta.persistence.fetchgraph", eg)
        .getResultList();
----

.Résumé
****
Cette nouveauté est intéressante. +
Les EntityGraph sont très efficaces pour traiter le problème N+1 et les quelques améliorations sont bienvenues.
****

=== Simplification JPQL
JPA 3.2 apporte quelques nouveautés sur les requêtes JPQL.

* Simplification des requêtes simples :

`SELECT b FROM Book b where b.title like :expression:` devient `FROM Book where b.title like :expression:`

La clause `SELECT` est facultative dans le cas où ou veut simplement retourner l'entité sélectionnée. +
L'alias `b` n'est pas nécessaire quand la requête ne travaille que sur une entité.

* Opérations ensemblistes :
```
SELECT name FROM Person
UNION
SELECT name FROM Organization
```

`union`, `intercept` et `except` étaient implémentés par certains ORM sans être officiellement disponibles dans JPA. Ces opérations font maintenant disponibles dans JPA 3.2. +

* Expressions dans les jointures :

`from Author a join Customer c on a.name = c.firstName||' '||c.lastName` : il est maintenant possible de mettre des expressions dans les jointures

* Nouvelles fonctions :
`select cast(left(fileName,2) as Integer) as chapter from Document` JPA 3.2 propose les nouvelles fonctions `cast`, `left`, `right`, `replace`, `id` et `version`, l'opérateur `||` est aussi disponible en alternative à `concat`

* Amélioration du tri :
`from Book order by lower(title) asc, publicationDate desc nulls first` les fonctions scalaires comme `lower` sont utilisables dans les tris. Il est aussi possible de décider où placer les `null` en spécifiant `nulls first` ou `nulls last`.

.Résumé
****
Ces quelques nouveautés JPQL ne révolutionnent pas JPA mais sont les bienvenues.
****

== Hibernate 7
=== @EmbeddedColumnNaming

Les types embarqués existent depuis un moment mais étaient limités.

Ils permettent de découper une table avec de nombreuses colonnes en plusieurs objets.
Typiquement, une table "Personnes" aura des colonnes pour son adresse (rue, code postal, ...)

|===
| id | first_name | last_name | city | street | zip_code
| | | | | |
|===

L'entité peut être découpée avec son type embarqué :

[source,java]
----
@Entity
@Table(name = "Personnes")
public class Person {
    @Id
    @GeneratedValue
    private Long id;

    private String firstName;

    private String lastName;

    @Embedded
    private Address address;

    //...
}

@Embeddable
public class Address {
    private String city;

    private String street;

    private String zipCode;
}
----

Cependant, jusqu'à Hibernate 7, les types embarqués étaient limités.

En effet, le mapping se faisait exclusivement avec le nom des propriétés (qui devaient correspondre au nom des colonnes en BDD).
Dans le cas où notre personne dispose de plusieurs adresses, les `@Embedded` n'étaient pas possible, sans https://docs.jboss.org/hibernate/orm/7.0/userguide/html_single/Hibernate_User_Guide.html#embeddable-override[solution de contournement complexe et extrêmement verbeuse] (utilisation de `@AttributeOverride` et `@AttributeOverrides`).

Pour remédier à ce problème, Hibernate 7 propose `@EmbeddedColumnNaming`, permettant d'utiliser plusieurs fois le même type embarqué avec un pattern:

[source,java]
----
@Entity
@Table(name = "Personnes")
public class Person {
    @Id
    @GeneratedValue
    private Long id;

    private String firstName;

    private String lastName;

    @Embedded
    @EmbeddedColumnNaming("home_%s")
    private Address homeAddress;

    @Embedded
    @EmbeddedColumnNaming("work_%s")
    private Address workAddress;

    //...
}

@Embeddable
public class Address {
    private String city;

    private String street;

    private String zipCode;
}
----

Les patterns `home_%` et `work_%` impliquent une table initialisée de cette manière :

|===
| id | first_name | last_name | home_city | home_street | home_zip_code | work_city | work_street | work_zip_code
| | | | | | | | |
|===

.Résumé
****
Le type `Embedabble` est maintenant utilisable plusieurs fois dans un même objet, cette évolution ne sera peut être pas utile tout le temps, mais elle est la bienvenue !
****

=== @NamedEntityGraph

Les `EntityGraph` existent depuis JPA 2.1, voir <<note2>>.

La fonctionnalité, propre à JPA, peut être complexe à prendre en main. Hibernate propose maintenant son annotation `@NamedEntityGraph`, plus simple à utiliser. +
Attention, une annotation JPA du même nom existe depuis plus longtemps, nous parlons ici de celle d'Hibernate.

Le principe est le suivant : on initialise un graph, au format String, il décrit quelles seront les associations à récupérer directement dans la requête jouée par Hibernate.

[source, java]
----
@Entity
@Table(name = "Shops")
@NamedEntityGraph(name = "Shop.withEmployees", graph = "employees")
@NamedEntityGraph(name = "Shop.withBooksAndTheirAuthor", graph = "books(author)")
public class Shop {
    @Id
    @GeneratedValue
    private Long id;

    @Embedded
    private Address address;

    @ManyToOne(fetch = FetchType.LAZY)
    private Person owner;

    @ManyToMany(fetch = FetchType.LAZY)
    private Collection<Person> employees;

    @ManyToMany(fetch = FetchType.LAZY)
    private Collection<Book> books;
}
----

Ici, par défaut on peut mettre toutes les associations en `LAZY`, on initialise plusieurs `@NamedEntityGraph`, dans lesquels on spécifie quelles associations sont à initialiser :

- Un graph pour récupérer les `Shop` avec leurs `employees` (étant une association de type `@ManyToMany`)
- Un graph pour récupérer les `Shop` avec leurs `books`(étant une association de `Shop`) et avec leurs `author` (étant eux même une association de `Book`) : il s'agit de graphe, on peut imbriquer autant d'associations qu'on veut.

Pour exécuter l'entity graph :

[source, java]
----
// cas d'un findById
Shop s1, s2;
// Cas classique, sans entity graph
s1 = session.find(id);
// Avec entity graph
EntityGraph<Shop> entityGraph1 = (EntityGraph<Shop>) session.getEntityGraph("Shop.withEmployees");
s2 = session.find(entityGraph1, id);

// cas d'un findAll
List<Shop> l1, l2;
// Cas classique, sans entity graph
l1 = session
    .createQuery("from Shop")
    .getResultList();
// Avec entity graph
EntityGraph<Shop> entityGraph2 = (EntityGraph<Shop>) session.getEntityGraph("Shop.withBooksAndTheirAuthor");
l2 = session
    .createQuery("from Shop")
    .setHint("jakarta.persistence.fetchgraph", entityGraph2)
    .getResultList();
----

L'intérêt est qu'on peut facilement choisir quelles associations seront chargées, pour afficher par exemple deux IHM différentes : un tableau affichant les boutiques et leurs employés, un autre affichant les boutiques, leurs livres et auteurs.

WARNING: la documentation suggère qu'il est aussi possible d'inclure des propriétés "classiques" dans le graphe : c'est à dire lazy load des colonnes et non uniquement des associations. Même si JPA le permet, cela dépend de la librairie qui l'implémente et par défaut Hibernate ne permet pas de lazy loader des propriétés ! +
Voir <<note3>>

.Résumé
****
Sans doute l'évolution d'Hibernate 7 la plus importante à retenir ! Les EntityGraph de JPA sont assez complexes à prendre en main mais sont pourtant une solution efficace et flexible concernant le problème N+1. Cette nouvelle annotation rend le principe d'EntityGraph plutôt simple à prendre en main. Point d'attention en revanche, le `@NamedEntityGraph` d'hibernate ne doit pas être confondu avec le `@NamedEntityGraph` de JPA, une différence notable est que le `@NamedEntityGraph` d'Hibernate n'est pas disponible dans le metamodel.
****

== Remarques

=== `EntityGraph` et problème N+1 [[note1]]

Le problème N+1 est bien connu, est compliqué à contourner et a un gros impact sur les performances d'une application:

Par défaut, les entités se chargent en mode lazy. Il faut initialiser les associations à la main (par exemple lors des appels `getMonAssociation()`), ce qui peut être fastidieux à mettre en place et à maintenir. Le coût en performance est important, pour chaque association à initialiser, une nouvelle requête sera jouée, *c'est là qu'apparaît le problème N+1* . +
De plus, lorsqu'on a besoin de la donnée, on se retrouve souvent dans une portion de code où il n'y a plus de contexte de persistence (ou session au sens Hibernate) ce qui devient souvent casse tête et pousse à produire du code un peu n'importe où, pourvu que ca passe et qu'une session soit ouverte, pour initialiser l'objet et ses associations ...

Une solution de contournement est de passer en mode eager. Lors de la récupération d'un objet, ses associations sont récupérées, les associations des associations seront elles aussi récupérées, etc ... quand en réalité, on a besoin uniquement de quelques colonnes. Si côté entités, toutes les associations sont mappées, la récupération d'un objet peut nécessiter de récupérer une grande partie du schéma. Les performances deviennent désastreuses au prix de contourner totalement le problème N+1...

Mixer le mode eager et le mode lazy ne convient pas non plus : on se retrouve dans des cas où, pour une autre IHM, on a besoin de charger des associations différentes. Quoi qu'il arrive, le casse tête est incessant ...

Plusieurs vraies solutions existent :

- Écrire des requêtes `JPQL` et utiliser https://www.baeldung.com/jpa-join-types#fetch[JOIN FETCH] qui a pour effet de récupérer une association : Fonctionne bien mais nécessite de faire des requêtes JPQL, pas forcément réutilisables, partout au cas par cas.
- Utiliser https://docs.jboss.org/hibernate/orm/6.5/javadocs/org/hibernate/annotations/BatchSize.html[@BatchSize] : ne règle pas directement le problème, mais permet de réduire grandement le nombre de requêtes lancées (au lieu de récupérer les associations unes par unes, on les récupères par lots de X). C'est plutôt une solution à utiliser en *complément* d'autres optimisations.
- Dupliquer des entités, mapper les propriétés autrement (faire l'équivalent de vues SQL): verbeux, nécessite de dupliquer et si une table change, risque d'impact sur un plus grand nombre de classes
- Finalement, les https://www.baeldung.com/jpa-entity-graph[EntityGraph], permettant de définir au travers d'un objet, l'arbre d'association à initialiser. Ce qui est flexible, car réutilisable dans la plupart des méthodes (criteria, find, méthodes de pagination) là où une requête JPQL est plus difficilement réutilisable.


Sur le principe, un objet `EntityGraph` est simple à utiliser : on l'instancie en indiquant quelles associations doivent êtres initialisées. Ensuite, lors d'appels, que ce soit `JQPL`, `EntityManager` ou `Criteria`, on peut passer cet `EntityGraph` en paramètre.

Toutes les entités auront les bonnes associations chargées automatiquement, dès leur récupération en BDD.

[source, java]
----
EntityGraph<Shop> eg = entityManager.createEntityGraph(Project.class);
eg.addElementSubgraph(Project_.employees)
        .addAttributeNodes(Employee_.department);

return em.createQuery("FROM Project", Project.class)
        .setHint("jakarta.persistence.fetchgraph", eg)
        .getResultList();
----


=== Le Metamodel [[note2]]

Le Metamodel n'est pas nouveau dans JPA et existe depuis JPA 2.

Historiquement, la définition de `Criterias` passait obligatoirement par l'usage, en dur, des noms des tables, colonnes puis la définition manuelle des types.

[source,java]
----
List<Shop> shops = this.sessionFactory.callInTransaction(em -> {
            CriteriaBuilder cb = em.getCriteriaBuilder();
            CriteriaQuery<Shop> cr = cb.createQuery(Shop.class);
            Root<Shop> root = cr.from(Shop.class);
            cr.select(root);
            cr.where(
                    cb.and(
                            cb.equal(root.<Long>get("id"), ownerId),
                            cb.equal(root.<Address>get("address").<String>get("city"), "Pessac")));

            return em
                    .createQuery(cr)
                    .setHint("jakarta.persistence.fetchgraph", em.getEntityGraph("Shop.withEmployees"))
                    .getResultList();

        });
----

Cela induisait plusieurs complexités :

- `root.<Long>get("id")` : Le nom de la colonne est en dur. Une variable statique peut être créée mais si le nom de la colonne vient à changer, la variable doit être mise à jour

- `<Long>get(...)` : Il est de la responsabilité du développeur de typer correctement l'appel, ce qui en plus d'être verbeux, peut être source d'erreur (rien n'empêche de mettre un mauvais type et avoir des erreurs de cast au runtime) et les mêmes problèmes se posent en cas de refactoring. En pratique, le type générique est souvent omis et on se retrouve avec des warnings dans le code et un code potentiellement imprévisible qui n'est pas type-safe

Globalement, les criterias ne sont pas type safe, et si une mauvaise colonne est utilisée, on ne s'en rend compte que trop tard, au runtime.

Un ORM implémentant JPA 2 (et plus) doit permettre de générer des classes *metamodel*, décrivant les colonnes et types de chaque classes.

Pour Hibernate, un simple ajout d'une dépendance précise permettra de générer les classes *metamodel* pour chaque entité, lors du build.

[source,xml]
----
<dependency>
    <groupId>org.hibernate.orm</groupId>
    <artifactId>hibernate-processor</artifactId>
    <version>7.0.3.Final</version>
</dependency>
----

[source,java]
----
@StaticMetamodel(Book.class)
public abstract class Book_ {
    public static final String ID = "id";
    public static final String TITLE = "title";
    public static final String AUTHOR = "author";
    public static final String SHOPS = "shops";
    public static volatile EntityType<Book> class_;
    public static volatile SingularAttribute<Book, Long> id;
    public static volatile SingularAttribute<Book, String> title;
    public static volatile SingularAttribute<Book, Person> author;
    public static volatile CollectionAttribute<Book, Shop> shops;

    public Book_() {
    }
}
----

Cette classe peut ensuite être utilisée dans l'API Criteria :
[source,java]
----
List<Shop> shops = this.sessionFactory.callInTransaction(em -> {
    CriteriaBuilder cb = em.getCriteriaBuilder();
    CriteriaQuery<Shop> cr = cb.createQuery(Shop.class);
    Root<Shop> root = cr.from(Shop.class);
    cr.select(root);
    cr.where(
            cb.and(
                    cb.equal(root.get(Shop_.owner), ownerId),
                    cb.equal(root.get(Shop_.address).get(Address_.city), "Pessac")));

    return em
            .createQuery(cr)
            .setHint("jakarta.persistence.fetchgraph", em.getEntityGraph("Shop.withEmployees"))
            .getResultList();

});
----

Par exemple, `root.<Address>get("address").<String>get("city")` devient `root.get(Shop_.address).get(Address_.city)`.

On peut donc :

- S'affranchir des noms de colonnes et types en durs. Il n'y a plus de risques liés aux types et aux refactoring
- Éviter les problèmes de mauvaises colonnes et mauvais type qui plantent au runtime, tout est safe et vérifié lors de la compilation. Si une mauvaise colonne et/ou un mauvais type sont utilisés, l'application ne buildera pas.

Le `metamodel` n'est évidemment pas obligatoire, il s'agit uniquement d'un confort supplémentaire pour l'API `Criteria`.

=== Remarques sur le lazy load Hibernate [[note3]]

La https://docs.jboss.org/hibernate/orm/7.0/userguide/html_single/Hibernate_User_Guide.html#fetching-strategies-dynamic-fetching-entity-graph-parsing-annotation[documentation sur les `@NamedEntityGraph`] suggère qu'il est possible de lazy-load des propriétés (en plus des associations) :

[source,java]
----
@Entity
@NamedEntityGraph( graph="title,isbn,author(name,phoneNumber)" )
class Book {
// ...
}
----

Ici, on ne charge que les propriétés `title` et `isbn`. Pour les auteurs, on ne charge que `name` et `phoneNumber` : le reste sera à null.

Ce n'est pourtant pas possible :

JPA propose une https://docs.jboss.org/hibernate/orm/7.0/userguide/html_single/Hibernate_User_Guide.html#basic-basic-annotation[annotation] `@Basic(optional = true, fetch = FetchType.LAZY)` (qui est facultative) à placer sur les propriétés "classiques" d'une entité (c-a-d, les propriétés autres que associations `@OneTo...` `@ManyTo...`).

[source,java]
----
@Entity
@Table(name = "Personnes")
public class Person {
    @Id
    @GeneratedValue
    private Long id;

    @Basic(fetch = FetchType.LAZY)
    private String firstName;

    @Basic(fetch = FetchType.LAZY)
    private String lastName;
}
----

C'est une annotation *JPA* et non *Hibernate*. Le paramètre `fetch` n'est, d'après la documentation, qu'un hint donné à JPA, mais la capacitié de lazy-loader une *propriété*  est au final le choix de l'implémentation, ici Hibernate et non de JPA.

Par défaut, Hibernate ignore ce paramètre, à moins d'activer le plugin https://docs.jboss.org/hibernate/orm/7.0/userguide/html_single/Hibernate_User_Guide.html#BytecodeEnhancement[bytecode enhancement] et mettre la propriété `enableLazyInitialization` à `true`.

[source,xml]
----
<build>
		<plugins>
            ...
			<plugin>
				<groupId>org.hibernate.orm.tooling</groupId>
				<artifactId>hibernate-enhance-maven-plugin</artifactId>
<!-- Il faut mettre EXACTEMENT la même version que la dépendance hibernate ! -->

				<version>7.0.0.Beta1</version>
				<executions>
					<execution>
						<configuration>
							<failOnError>true</failOnError>
							<enableLazyInitialization>true</enableLazyInitialization>
						</configuration>
						<goals>
							<goal>enhance</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
----

Le plugin doit être sur la même version qu'Hibernate mais n'est aujourd'hui disponible qu'en Beta et non en version finale, causant actuellement des problèmes de compatibilité :

Le lazy load sur Hibernate par défaut se limite aux *associations* et il est conseillé de rester sur ce fonctionnement.

Donc il vaut mieux considérer le lazy load de propriété, sur les EntityGraph impossible


== Conclusion

Ces versions majeures d'Hibernate 7 et JPA 3.2 sont très intéressantes.

Certaines features sont peu impactantes (options, configuration dynamique), d'autres peuvent s'avérer utiles (amélioration metamodel et type Embedable) et finalement d'autres sont très importantes asbolument à retenir (@NamedEntityGraph) et certainement même à adopter si Hibernate 7 est disponible sur les projets.
